### ISSUE TITLE
Issue 2 Create Event Category Class

### ISSUE THREAD

**Issue by kaurgurpal** [kaurgurpal/Eventbrite#2]
define the properties to have in EventCategory class

**Comment by LeelaCreations** [comment]
1. Name Conflict with Namespace EventCatalog. Hence changed the name of EventCatalog class to EventsCatalog. But I would suggest a change of name space deom EventCatalog to EventCatalogAPI. 

2. I felt like, we need separate table for Organizer in case if we want to see the details of Organizer or want to see all the events conducted by a specific organizer. This can be removed, if you guys feel otherwise.
